{
 "title": "WAF",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "description": "An administratively-assigned name for this managed node. By convention, this is the node's fully-qualified domain name",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"uptime\") FROM \"snmp\" WHERE (\"host\" = 'telegraf') AND $timeFilter GROUP BY time(1m), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "The time (in hundredths of a second) since the network management portion of the system was last re-initialized",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"uptime\") FROM \"snmp\" WHERE (\"host\" = 'telegraf') AND $timeFilter GROUP BY time(1m), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Operation mode of the device",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Operation Mode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"uptime\") FROM \"snmp\" WHERE (\"host\" = 'telegraf') AND $timeFilter GROUP BY time(1m), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "operation-mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "High-availability mode",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "HA Mode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"uptime\") FROM \"snmp\" WHERE (\"host\" = 'telegraf') AND $timeFilter GROUP BY time(1m), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "ha-mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Firmware version of the device",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "OS Version",
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"os_version\") FROM \"Afranet-R5_interfaces\" WHERE $timeFilter GROUP BY \"hostname\"",
     "select": [
      [
       { "params": [ "os_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "The number of CPU",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Number of CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"uptime\") FROM \"snmp\" WHERE (\"host\" = 'telegraf') AND $timeFilter GROUP BY time(1m), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "cpu-total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total physical memory (RAM) installed",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RAM Capacity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"uptime\") FROM \"snmp\" WHERE (\"host\" = 'telegraf') AND $timeFilter GROUP BY time(1m), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "memory-total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total hard disk capacity",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Disk Capacity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"uptime\") FROM \"snmp\" WHERE (\"host\" = 'telegraf') AND $timeFilter GROUP BY time(1m), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "disk-total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Current CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "YOUR-NAME",
     "select": [
      [
       { "params": [ "cpu-usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "description": "Current CPU frequency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "alias": "usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "YOUR-NAME",
     "select": [
      [
       { "params": [ "cpu-frequency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Current memory utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "YOUR-NAME",
     "select": [
      [
       { "params": [ "memory-utilization" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Current hard disk usage rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "YOUR-NAME",
     "select": [
      [
       { "params": [ "disk-usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Send Rate",
   "type": "timeseries",
   "description": "The total number of octets transmitted on the interface, including framing characters. Discontinuities in the value of this counter can occur at re-initialization of the management system, and at other times as indicated by the value of ifCounterDiscontinuityTime",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  NON_NEGATIVE_DERIVATIVE(last(\"ifOutOctets\"), 1s) *8 FROM \"YOUR-NAME\" WHERE (\"ifOperStatus\"=1) AND $timeFilter GROUP BY time($__interval), \"ifName\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Receive Rate",
   "type": "timeseries",
   "description": "The total number of octets received on the interface, including framing characters. Discontinuities in the value of this counter can occur at re-initialization of the management system, and at other times as indicated by the value of ifCounterDiscontinuityTime",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  NON_NEGATIVE_DERIVATIVE(last(\"ifInOctets\"), 1s) *8 FROM \"YOUR-NAME\" WHERE (\"ifOperStatus\"=1) AND $timeFilter GROUP BY time($__interval), \"ifName\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Port Summary",
   "type": "table",
   "description": "An entry containing management information applicable to a particular interface",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ifIndex" ], "type": "tag" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "YOUR-NAME",
     "select": [
      [
       { "params": [ "ifAlias" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifHighSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *1000000" ], "type": "math" }
      ],
      [
       { "params": [ "ifInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifType" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}